### ISSUE TITLE
Very basic setup - please help

### ISSUE THREAD

**Issue by NCSL2020** [Ifsttar/NoiseModelling#101]
Hi all, I hope you are all well!

I'm really interested in using this software, but I'm struggling to get it set up (my computing knowledge isn't really up to these standards!).

I have Java installed, I have Orbisgis installed and running, and I have the NoiseModel folder downloaded. What I can't figure out is how to get them to work together - does NoiseModel need to be opened via Orbisgis?

Please accept my appolgies for such a basic question, and thanks in advance for any help offered.

Best

AT

**Comment by pierromond** [comment]
Dear AT,

Thank you very much for your interest. Last year, you couldn't do noise modeling without OrbisGis. But since then these two softwares are complementary but independent.

OrbisGis will be very useful if you want to manage your database or perform spatial processing on input or output layers but noise maps can be perform using NoiseModelling standalone.

Have you seen the latest documentation of NoiseModelling*? You can do the tutorial and I think it will answer most of your questions.

> https://noisemodelling.readthedocs.io/en/latest/

Feel free to comment on this tutorial and ask any new questions you may have,

Best regards.
