### ISSUE TITLE
Why the building geometry in 2d and roads geometry in 3d?

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#148]
Check THE_GEOM column of the building and the road table, why has the difference?

**Comment by whywayne2020** [comment]
How can I transferm between 2d and 3d geometry, most geometry from shape file are in 2D.

**Comment by pierromond** [comment]
The building geometry is not needed because, the first floor has to be stucked to the ground, and the height of the building is given by the Height field.

The 3D road geometry is needed, because the height of each sound source if given by the z value of the THE_GEOM field.

To convert a 2D geometry to 3D geometry, you can use SQL with H2GIS for example, but also your favorite GIS program. Maybe you can also try to create a WPS Block which can add a unique z-value to a table.

**Comment by whywayne2020** [comment]
thanks, How about  the buildings not on the same ground level? so the DEM table is must demand?

**Comment by pierromond** [comment]
Your case is very complicated because of the CNOSSOS-EU model limitations. Maybe a building acoustics software could me more adapated as I-Simpa. But... 

If you give the corresponding DEM input (it will correspond to the bottom elevation) and the 2D position and height of the building, you should have sthg similar to your figure.
