### ISSUE TITLE
Installation issue - startup.bat

### ISSUE THREAD

**Issue by LAFFITTEElodie** [Ifsttar/NoiseModelling#188]
Hi everyone ! 

I will really abuse of your kindness but i am still installing NoiseModelling avec finally find the famous startup.bat to launch geoserver ... but when i launch it, it displays "Welcome to Geoserver! Syntax instruction not correct" . I tried to look into the file but everything seems ok... after adding some "echo" to find the bug, it seems to be the first instruction to be wrong: 
"if "%JAVA_HOME%" == "" goto trySystemJava "

- is trySystemJava not found or is it something else? what can i do? 
step 1 (installing java home at correct place was ok...

Thank for your help

Elodie

**Comment by pierromond** [comment]
I think you have not completed the first step of the tutorial correctly. Try again, taking care to validate each step. You must install JAVA and its environment variable correctly.

https://noisemodelling.readthedocs.io/en/latest/Get_Started_Tutorial.html

`If you don’t have this result, it is probably because your JAVA_HOME environnement variable is not well settled. To set you JAVA_HOME environnement variable you can adapt (with x the JAVA version number) you installed and use the following command line : setx JAVA_HOME  "C:\Program Files (x86)\Java\jre.1.8.x" in your command prompt. You can also refer to this document for example.`

Good luck!

**Comment by LAFFITTEElodie** [comment]
thank you very much but i completely missed several things and among them, defining my system variables... it's ok now !
