### ISSUE TITLE
any roads inputed from OSM in CHINA area are displayed as a single horizontal line

### ISSUE THREAD

**Issue by weiba388** [Ifsttar/NoiseModelling#210]
**NoiseModelling version**
3.2.1

**Describe the bug**
any roads inputed from OSM database in CHINA area are display as a single horizontal line, by using Table_Visualization_Map fuction.
have tried beijing,changsha and other areas in CHINA.
buildings and ground tables are displayed correctly.

if ignore , then will report errors in Delaunar_Grid , as reported in issue #208

**Comment by pierromond** [comment]
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Geoserver log**

Attach geoserver log located in **data_dir\logs\geoserver.log**

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by weiba388** [comment]
sloved.
wrong EPSG code.
